### YamlMime:ManagedReference
items:
- uid: MapQuest.IO.AppSettingsManager
  commentId: T:MapQuest.IO.AppSettingsManager
  id: AppSettingsManager
  parent: MapQuest.IO
  children:
  - MapQuest.IO.AppSettingsManager.#ctor
  - MapQuest.IO.AppSettingsManager.GetDouble(System.String,System.Double)
  - MapQuest.IO.AppSettingsManager.GetInt32(System.String,System.Int32)
  - MapQuest.IO.AppSettingsManager.GetSingle(System.String,System.Single)
  - MapQuest.IO.AppSettingsManager.GetString(System.String,System.String)
  langs:
  - csharp
  - vb
  name: AppSettingsManager
  nameWithType: AppSettingsManager
  fullName: MapQuest.IO.AppSettingsManager
  type: Class
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public class AppSettingsManager
    content.vb: Public Class AppSettingsManager
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: MapQuest.IO.AppSettingsManager.GetString(System.String,System.String)
  commentId: M:MapQuest.IO.AppSettingsManager.GetString(System.String,System.String)
  id: GetString(System.String,System.String)
  parent: MapQuest.IO.AppSettingsManager
  langs:
  - csharp
  - vb
  name: GetString(string, string)
  nameWithType: AppSettingsManager.GetString(string, string)
  fullName: MapQuest.IO.AppSettingsManager.GetString(string, string)
  type: Method
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public static string GetString(string key, string defaultValue)
    parameters:
    - id: key
      type: System.String
    - id: defaultValue
      type: System.String
    return:
      type: System.String
    content.vb: Public Shared Function GetString(key As String, defaultValue As String) As String
  overload: MapQuest.IO.AppSettingsManager.GetString*
  nameWithType.vb: AppSettingsManager.GetString(String, String)
  fullName.vb: MapQuest.IO.AppSettingsManager.GetString(String, String)
  name.vb: GetString(String, String)
- uid: MapQuest.IO.AppSettingsManager.GetDouble(System.String,System.Double)
  commentId: M:MapQuest.IO.AppSettingsManager.GetDouble(System.String,System.Double)
  id: GetDouble(System.String,System.Double)
  parent: MapQuest.IO.AppSettingsManager
  langs:
  - csharp
  - vb
  name: GetDouble(string, double)
  nameWithType: AppSettingsManager.GetDouble(string, double)
  fullName: MapQuest.IO.AppSettingsManager.GetDouble(string, double)
  type: Method
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public static double GetDouble(string key, double defaultValue)
    parameters:
    - id: key
      type: System.String
    - id: defaultValue
      type: System.Double
    return:
      type: System.Double
    content.vb: Public Shared Function GetDouble(key As String, defaultValue As Double) As Double
  overload: MapQuest.IO.AppSettingsManager.GetDouble*
  nameWithType.vb: AppSettingsManager.GetDouble(String, Double)
  fullName.vb: MapQuest.IO.AppSettingsManager.GetDouble(String, Double)
  name.vb: GetDouble(String, Double)
- uid: MapQuest.IO.AppSettingsManager.GetSingle(System.String,System.Single)
  commentId: M:MapQuest.IO.AppSettingsManager.GetSingle(System.String,System.Single)
  id: GetSingle(System.String,System.Single)
  parent: MapQuest.IO.AppSettingsManager
  langs:
  - csharp
  - vb
  name: GetSingle(string, float)
  nameWithType: AppSettingsManager.GetSingle(string, float)
  fullName: MapQuest.IO.AppSettingsManager.GetSingle(string, float)
  type: Method
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public static float GetSingle(string key, float defaultValue)
    parameters:
    - id: key
      type: System.String
    - id: defaultValue
      type: System.Single
    return:
      type: System.Single
    content.vb: Public Shared Function GetSingle(key As String, defaultValue As Single) As Single
  overload: MapQuest.IO.AppSettingsManager.GetSingle*
  nameWithType.vb: AppSettingsManager.GetSingle(String, Single)
  fullName.vb: MapQuest.IO.AppSettingsManager.GetSingle(String, Single)
  name.vb: GetSingle(String, Single)
- uid: MapQuest.IO.AppSettingsManager.GetInt32(System.String,System.Int32)
  commentId: M:MapQuest.IO.AppSettingsManager.GetInt32(System.String,System.Int32)
  id: GetInt32(System.String,System.Int32)
  parent: MapQuest.IO.AppSettingsManager
  langs:
  - csharp
  - vb
  name: GetInt32(string, int)
  nameWithType: AppSettingsManager.GetInt32(string, int)
  fullName: MapQuest.IO.AppSettingsManager.GetInt32(string, int)
  type: Method
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public static int GetInt32(string key, int defaultValue)
    parameters:
    - id: key
      type: System.String
    - id: defaultValue
      type: System.Int32
    return:
      type: System.Int32
    content.vb: Public Shared Function GetInt32(key As String, defaultValue As Integer) As Integer
  overload: MapQuest.IO.AppSettingsManager.GetInt32*
  nameWithType.vb: AppSettingsManager.GetInt32(String, Integer)
  fullName.vb: MapQuest.IO.AppSettingsManager.GetInt32(String, Integer)
  name.vb: GetInt32(String, Integer)
- uid: MapQuest.IO.AppSettingsManager.#ctor
  commentId: M:MapQuest.IO.AppSettingsManager.#ctor
  id: '#ctor'
  parent: MapQuest.IO.AppSettingsManager
  langs:
  - csharp
  - vb
  name: AppSettingsManager()
  nameWithType: AppSettingsManager.AppSettingsManager()
  fullName: MapQuest.IO.AppSettingsManager.AppSettingsManager()
  type: Constructor
  assemblies:
  - MapQuest.Core
  namespace: MapQuest.IO
  syntax:
    content: public AppSettingsManager()
    content.vb: Public Sub New()
  overload: MapQuest.IO.AppSettingsManager.#ctor*
  nameWithType.vb: AppSettingsManager.New()
  fullName.vb: MapQuest.IO.AppSettingsManager.New()
  name.vb: New()
references:
- uid: MapQuest.IO
  commentId: N:MapQuest.IO
  isExternal: true
  href: MapQuest.html
  name: MapQuest.IO
  nameWithType: MapQuest.IO
  fullName: MapQuest.IO
  spec.csharp:
  - uid: MapQuest
    name: MapQuest
    isExternal: true
    href: MapQuest.html
  - name: .
  - uid: MapQuest.IO
    name: IO
    isExternal: true
    href: MapQuest.IO.html
  spec.vb:
  - uid: MapQuest
    name: MapQuest
    isExternal: true
    href: MapQuest.html
  - name: .
  - uid: MapQuest.IO
    name: IO
    isExternal: true
    href: MapQuest.IO.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MapQuest.IO.AppSettingsManager.GetString*
  commentId: Overload:MapQuest.IO.AppSettingsManager.GetString
  isExternal: true
  href: MapQuest.IO.AppSettingsManager.html#MapQuest_IO_AppSettingsManager_GetString_System_String_System_String_
  name: GetString
  nameWithType: AppSettingsManager.GetString
  fullName: MapQuest.IO.AppSettingsManager.GetString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MapQuest.IO.AppSettingsManager.GetDouble*
  commentId: Overload:MapQuest.IO.AppSettingsManager.GetDouble
  isExternal: true
  href: MapQuest.IO.AppSettingsManager.html#MapQuest_IO_AppSettingsManager_GetDouble_System_String_System_Double_
  name: GetDouble
  nameWithType: AppSettingsManager.GetDouble
  fullName: MapQuest.IO.AppSettingsManager.GetDouble
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: MapQuest.IO.AppSettingsManager.GetSingle*
  commentId: Overload:MapQuest.IO.AppSettingsManager.GetSingle
  isExternal: true
  href: MapQuest.IO.AppSettingsManager.html#MapQuest_IO_AppSettingsManager_GetSingle_System_String_System_Single_
  name: GetSingle
  nameWithType: AppSettingsManager.GetSingle
  fullName: MapQuest.IO.AppSettingsManager.GetSingle
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: MapQuest.IO.AppSettingsManager.GetInt32*
  commentId: Overload:MapQuest.IO.AppSettingsManager.GetInt32
  isExternal: true
  href: MapQuest.IO.AppSettingsManager.html#MapQuest_IO_AppSettingsManager_GetInt32_System_String_System_Int32_
  name: GetInt32
  nameWithType: AppSettingsManager.GetInt32
  fullName: MapQuest.IO.AppSettingsManager.GetInt32
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: MapQuest.IO.AppSettingsManager.#ctor*
  commentId: Overload:MapQuest.IO.AppSettingsManager.#ctor
  isExternal: true
  href: MapQuest.IO.AppSettingsManager.html#MapQuest_IO_AppSettingsManager__ctor
  name: AppSettingsManager
  nameWithType: AppSettingsManager.AppSettingsManager
  fullName: MapQuest.IO.AppSettingsManager.AppSettingsManager
  nameWithType.vb: AppSettingsManager.New
  fullName.vb: MapQuest.IO.AppSettingsManager.New
  name.vb: New
